spring:
  application:
    name: order-gateway

  # gateway
  cloud:
    gateway:
      routes:
        - id: order-gateway-id
          uri: lb://cloud-payment
          order: 0
          predicates:
#            - Path=/payment/{id}
            - Method=GET
#            - Query=id,\d+
          filters:
#            添加请求头
            - AddRequestHeader=id,10
#            添加统一的请求路径
            - PrefixPath=/payment


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.server.com:1010/eureka/  #服务注册地址
    registry-fetch-interval-seconds: 5  #eureka client配置5s从server同步一次服务列表

server:
  port: 80