spring:
  application:
    name: cloud-order

  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/sundz?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&relaxAutoCommit=true&autoCommit=true&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/sundz?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&relaxAutoCommit=true&autoCommit=true&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 2020

mybatis:
  mapper-locations: classpath:/mapper/*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.server.com:1010/eureka/  #服务注册地址
    registry-fetch-interval-seconds: 5  #eureka client配置5s从server同步一次服务列表

ribbon:
  eager-load:
    enabled: true

#开启feign支持hystrix  (注意，一定要开启，旧版本默认支持，新版本默认关闭)
# #修改调用超时时间（默认是1秒就算超时）
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

